### ISSUE TITLE
[Bug]: The route forgot-password could not be found

### ISSUE THREAD

**Issue by nathanmay** [vormkracht10/filament-2fa#59]
### What happened?

Since upgrading to the version 2.0.0 and following the upgrade notes of this package, the forgotten password link no longer works on the login page (screenshot below of the link I'm referring to).

![image](https://github.com/user-attachments/assets/42da3298-e09b-4cd7-8996-abf3b7e8ded5)

I have uninstalled the package and then the forgotten password link works perfectly again. 

I have even installed the plugin again, republishing all the files but the same error occurs.

### How to reproduce the bug

When clicking on the 'Forgot password?' link on the login page it simply returns a 404 error.

### Repository

filament-2fa

### Package Version

2.0.0

### PHP Version

8.2

### Laravel Version

11.32

### Which operating systems does with happen with?

Windows

**Comment by Baspa** [comment]
@nathanmay I found the cause of this issue, I'm working on a fix

**Comment by cawecoy** [comment]
@Baspa @nathanmay any update?

**Comment by cawecoy** [comment]
@Baspa @nathanmay I found a solution, it worked for me, let me know if it works for you.

Update `config/filament-2fa.php`:

```

'login' => \Filament\Pages\Auth\Login:class,
'register' => \Filament\Pages\Auth\Register::class,
'password_reset' => \Filament\Pages\Auth\PasswordReset\ResetPassword::class,
'request_password_reset' => Filament\Pages\Auth\PasswordReset\RequestPasswordReset::class,
```

Those are default Filament classes for login, register and password reset. But if you use custom classes for login, register and password reset on you Filament panel, you should use those classes instead of the Filament default ones.
